name: dgbpy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install odpy
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==1.23.5
        python -m pip install h5py==3.8.0
        python -m pip install numba==0.56.4
        python -m pip install git+https://github.com/OpendTect/odpy.git
    - name: Install  dgbpy
      run: |
        pip install flake8 pytest
        python -m pip install bokeh==3.1.0
        python -m pip install joblib==1.2.0
        python -m pip install scikit-learn==1.2.2
        python -m pip install torch==2.0.0+cu113 cudnn==8.4.1
        python -m pip install tensorflow==2.11.0
        python -m pip install onnx==1.13.1
        python -m pip install onnxruntime-gpu==1.14.1
        python -m pip install onnx2torch==1.5.6
        python -m pip install opencv-python==4.7.0
        python -m pip install xgboost==1.7.4
        python -m pip install .
    - name: Get test examplefiles
      run: |
        cd tests
        mkdir examples
        wget "https://github.com/OpendTect/OpendTect-ML-Dev/raw/main/webinars/2021-04-22/Examples/data/Log_-_Lithology_supervised_prediction.h5" -O "examples/Log_-_Lithology_supervised_prediction.h5"
        wget "https://github.com/OpendTect/OpendTect-ML-Dev/raw/main/webinars/2021-04-22/Examples/data/Layers_input_2D.h5" -O "examples/Layers_input_2D.h5"
        wget "https://github.com/OpendTect/OpendTect-ML-Dev/raw/main/webinars/2021-04-22/Examples/data/malenov_input_8x8x16_subsample_dBG.h5" -O "examples/malenov_input_8x8x16_subsample_dBG.h5"
        wget "https://github.com/OpendTect/OpendTect-ML-Dev/raw/main/webinars/2021-04-22/Examples/data/Log_-_density.h5" -O "examples/Log_-_density.h5"
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --ignore=F824  --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run ML Workflow Tests
      run: |
        pytest


    
